version: '3.8'

services:
  api2:
    build: .

  api1:
    build: .

  nginx:
    image: nginx:mainline
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"

  redis:
    image: redis:latest