version: '3.8'

services:
  users1:
    build: .
    command: python manage.py runserver 0.0.0.0:8001

  user1-consumer:
    build: .
    command: python manage.py run_consumer

  users2:
    build: .
    command: python manage.py runserver 0.0.0.0:8001

  user2-consumer:
    build: .
    command: python manage.py run_consumer

  nginx:
    image: nginx:mainline
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "81:80"
