version: '3.8'

services:
  users1:
    build: .

  users2:
    build: .

  nginx:
    image: nginx:mainline
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "81:80"

  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"  # RabbitMQ client connection
      - "15672:15672"  # RabbitMQ management UI
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq  # Persist RabbitMQ data

volumes:
  rabbitmq_data:
