version: '3.8'

services:
  users1:
    build: .

  users2:
    build: .

  nginx:
    image: nginx:mainline
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "81:80"