# Generated by Django 5.1.2 on 2024-10-20 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="user_id",
            field=models.UUIDField(),
        ),
    ]
