version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  db-replica:
    image: postgres:13
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data_replica:/var/lib/postgresql/data

  nginx:
    image: nginx:mainline
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - web-1
      - web-2
      - web-3

  web-1:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db

  web-2:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db

  web-3:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db

volumes:
  postgres_data:
  postgres_data_replica:
