  version: '3.8'

  services:
    db:
      image: postgres:13
      environment:
        POSTGRES_DB: postgres
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
      ports:
        - "5432:5432"
      volumes:
        - ./postgres_data:/var/lib/postgresql/data

    db-replica:
      image: postgres:13
      environment:
        POSTGRES_DB: postgres
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
      ports:
        - "5433:5432"
      volumes:
        - ./postgres_data_replica:/var/lib/postgresql/data
      depends_on:
        - db

    nginx:
      image: nginx:mainline
      volumes:
        - ./default.conf:/etc/nginx/conf.d/default.conf
      ports:
        - "80:80"
      depends_on:
        - web-1
        - web-2
        - web-3

    web-1:
      build: .
      command: python manage.py runserver 0.0.0.0:8000
      depends_on:
        - db
        - db-replica

    web-2:
      build: .
      command: python manage.py runserver 0.0.0.0:8000
      depends_on:
        - db
        - db-replica

    web-3:
      build: .
      command: python manage.py runserver 0.0.0.0:8000
      depends_on:
        - db
        - db-replica

    prometheus:
      image: prom/prometheus
      ports:
        - "9090:9090"

    grafana:
      image: grafana/grafana
      ports:
        - "3000:3000"
      volumes:
        - ./grafana_data:/var/lib/grafana
      depends_on:
        - prometheus

    elasticsearch:
      image: docker.elastic.co/elasticsearch/elasticsearch:8.4.0
      environment:
        - discovery.type=single-node
        - ES_JAVA_OPTS=-Xms512m -Xmx512m
      ports:
        - "9200:9200"
      volumes:
        - ./es_data:/usr/share/elasticsearch/data

    logstash:
      image: docker.elastic.co/logstash/logstash:8.4.0
      ports:
        - "5044:5044"
      volumes:
        - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf

    kibana:
      image: docker.elastic.co/kibana/kibana:8.4.0
      ports:
        - "5601:5601"
      depends_on:
        - elasticsearch

  volumes:
    postgres_data:
    postgres_data_replica:
    es_data:
    grafana_data:

