FROM python:3.10-slim


WORKDIR /app


COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt


COPY . .


ENV PYTHONUNBUFFERED 1
ENV DJANGO_SETTINGS_MODULE=tasks.settings


CMD ["celery", "-A", "tasks", "worker", "--loglevel=info"]
