version: '3.8'

services:
  users1:
    build:
      context: ./users
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000

  user1-consumer:
    build:
      context: ./users
      dockerfile: Dockerfile
    command: python manage.py run_consumer

  users2:
    build:
      context: ./users
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000

  user2-consumer:
    build:
      context: ./users
      dockerfile: Dockerfile
    command: python manage.py run_consumer

  nginx-users:
    image: nginx:mainline
    volumes:
      - ./users/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "81:80"

  api2:
    build:
      context: ./e-commerce
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000

  api1:
    build:
      context: ./e-commerce
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000

  nginx-api:
    image: nginx:mainline
    volumes:
      - ./e-commerce/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3.13.4-management
    ports:
      - "5672:5672"
      - "15672:15672"
